### ISSUE TITLE
ClosestPointToPointParameter in src/Line3.js

### ISSUE THREAD

**Issue by babara2** [chafey/cornerstoneMath#12]
This function returns another function that takes in a point and a 'clampToLine' parameter. However, within this inner function, the line's start and end are called but the function, at this point, has lost scope of the the start and end of line, and we get the error: 

undefined is not an object (evaluating 'this.start')

I am trying to write test for this function, and I suggest that instead of returning a function, why not just run the internal function directly? Once again, this might be a non-issue, but I find the issues page to be the most effective resource at resolving confusions such as this.
![screen shot 2018-02-24 at 9 01 58 pm](https://user-images.githubusercontent.com/16140001/36637694-278ace0c-19a7-11e8-9501-b50e65e36547.png)

**Comment by swederik** [comment]
I think we aren't actually using closestPointToPoint whatsoever in Cornerstone Tools, so maybe we should just remove it.
