### ISSUE TITLE
Issue during production build

### ISSUE THREAD

**Issue by pavankuppa** [chafey/cornerstoneMath#18]
In production mode modules the below is not considering as esModule

in Vector.js
```js
setFromCoplanarPoints: function(){
}
```
```r.default``` throws an error, while making it as ```r.default.default()``` then its working.
as per my understanding that webpack is not considering as esModule

**Comment by swederik** [comment]
I guess there's something weird about it being an IIFE... Thanks for the report.

**Comment by pavankuppa** [comment]
Any progress on this issue

**Comment by dannyrb** [comment]
@pavankuppa `cornerstone-math` is one of the less active libraries supported by our team. If you make a PR that addresses this issue, it's much more likely you'll see a merged fix in the near future.

**Comment by swederik** [comment]
I would just remove the function. I don't think we are using it at all.

**Comment by pavankuppa** [comment]
@dannyrb Thanks, but I don't know how to fix the build issue with ```cornerstoneMath.min.js``` file

**Comment by t-animal** [comment]
This issue affects my team, too.
I think it may be related to https://github.com/babel/babel/issues/3917 However I have too little insight into how the build process works to confirm this conclusively.
If you intend to fix it by removing `setFromCoplanarPoints` go ahead and remove `intersectLine`, too, as it is affected as well.

**Comment by Anduil** [comment]
I've got it bug too. Removing of setFromCoplanarPoints  and intersectLine functions was helpful. But it complicated, because using of such problem solution is really not convenient
