### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by wwwillchen** [chafey/cornerstoneMath#8]
Hello - I'm part of a healthcare team at Google that would like to use cornerstoneMath. Our open source compliance team raised up the issue that this repo mentions MIT but doesn't explicitly include the LICENSE file (similar to your main cornerstone repo: https://github.com/cornerstonejs/cornerstone/blob/master/LICENSE). Would you mind including the MIT License as a LICENSE file? Thank you. This would also help open the door for us to contribute a few patches.

**Comment by dannyrb** [comment]
Thanks for dropping in 👋 😄 
Feel free to hit up the other `cornerstone` repositories with issues and pull requests as you play around

https://github.com/cornerstonejs/cornerstoneMath/blob/master/LICENSE

**Comment by wwwillchen** [comment]
Thank you!
